# Hide default refind text, ui elements
# All are hidden by default only for the sake of minimalism
hideui arrows,hints,label,badges

# Set icon directory
icons_dir themes/refindTTL/icons

# Set background
# Custom backgrounds won't work well unless the center is entirely white
banner themes/refindTTT/backgrounds/background.png
banner_scale fillscreen

# Set icon sizes (default: 120, 256)
# Changing these will impact image quality; switch to 'theme176.conf' in 'refind.conf' for smaller icons
small_icon_size 120
big_icon_size 256

# Keeps the screen blank when launching an OS, prevents basic boot info from flashing on screen
use_graphics_for osx,linux,elilo,grub,windows

# Set background for selected option
# To hide text label change to 'selection_big_nolabels.png', 'selection_small_nolabels.png'
selection_big   themes/refindTTL/backgrounds/selection_big.png
selection_small themes/refindTTL/backgrounds/selection_small.png

# Set maximum icons to display at a time (divide screen width by 288)
max_tags 7

# Set delay before automatic boot
timeout 10
